---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-access
  namespace: argo-events
type: Opaque
data:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: argo-events
type: Opaque
data:
  token: ""
